spring.application.name=EduAnalytics-backend

spring.datasource.url=jdbc:h2:mem:eduanalytics
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

api.security.token.secret=${JWT_SECRET:my-secret-key}